backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Ajout image : {{slug}}'
    update: 'Mise Ã  jour image : {{slug}}'

media_folder: "images"
public_folder: "/images"

collections:
  - name: "costumes"
    label: "ğŸ‘” Costumes"
    folder: "images/costumes"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "chemises"
    label: "ğŸ‘• Chemises"
    folder: "images/chemises"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "pantalons"
    label: "ğŸ‘– Pantalons"
    folder: "images/pantalons"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
